if: branch = master

language: cpp

git:
  submodules: true
  depth: 5

os:
  - linux
dist: focal

env:
  global:  # default values
    - COMPILER=clang
    - PYTHON_VERSION=3.8
    - OS_NAME=linux
  matrix:
    - TASK=regular PYTHON_VERSION=3.6
    - TASK=sdist
    - TASK=bdist
    - TASK=if-else
    - TASK=mpi METHOD=source
    - TASK=mpi METHOD=pip PYTHON_VERSION=3.7
    - TASK=mpi METHOD=wheel PYTHON_VERSION=3.7
    - TASK=gpu METHOD=source
    - TASK=gpu METHOD=pip PYTHON_VERSION=3.6
    - TASK=gpu METHOD=wheel PYTHON_VERSION=3.7

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - export BUILD_DIRECTORY="$TRAVIS_BUILD_DIR"
  - export CONDA="$HOME/miniconda"
  - export PATH="$CONDA/bin:$PATH"
  - export CONDA_ENV="test-env"
  - export LGB_VER=$(head -n 1 VERSION.txt)
  - export AMDAPPSDK_PATH=$HOME/AMDAPPSDK
  - export LD_LIBRARY_PATH="$AMDAPPSDK_PATH/lib/x86_64:$LD_LIBRARY_PATH"
  - export LD_LIBRARY_PATH="/usr/local/clang/lib:$LD_LIBRARY_PATH"  # fix error "libomp.so: cannot open shared object file: No such file or directory" on Linux with Clang
  - export OPENCL_VENDOR_PATH=$AMDAPPSDK_PATH/etc/OpenCL/vendors

install:
  - bash .ci/setup.sh

script:
  - bash .ci/test.sh

notifications:
  email: false
